---
- name: Apply networkd changes
  become: true
  ansible.builtin.shell: |
    systemctl daemon-reload
    systemctl restart systemd-udev-trigger.service
    systemctl restart systemd-networkd
  async: 60
